[package]
name = "torkoal"
version = "0.1.0"
authors = ["7k, agent burks"]
edition = "2021"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
songbird = "0.3.1"
chatgpt_rs = "1.1.3"
random-string = "1.0"


[dependencies.serenity]
version = "0.11"
features = ["client", "standard_framework", "voice", "rustls_backend", "model"]

[dependencies.tokio]
version = "1.0"
features = ["macros", "rt-multi-thread", "signal"]
